/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Account;
import static Account.UserInfo.writeToEvent;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextArea;
import javax.swing.RowFilter;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author ozknsmz
 */
public class Admin_Panel extends javax.swing.JFrame {
int i=0;
         
     DefaultTableModel model ,model2;
 
     public void dinamicSearch(String search){//event 

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        table.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(search));
       }

     public void dinamicSearchforUser(String search){

        TableRowSorter<DefaultTableModel> dsfu = new TableRowSorter<>(model2);
        
        usertable.setRowSorter(dsfu);
        
        dsfu.setRowFilter(RowFilter.regexFilter(search));
       }

     
    public static JTextArea getTa() {
        return ta;
    }
     

 

    /**
     * Creates new form Admin_Panel
     */
    public Admin_Panel() {
        initComponents();
        setIcon();
       
        update.setVisible(false);
        add.setVisible(false);
      pancity.setVisible(false);
      pandate.setVisible(false);
   bsend.setVisible(false);
        tableuser.setVisible(false);
        ta.setVisible(false);     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton4 = new javax.swing.JButton();
        admin = new javax.swing.JTabbedPane();
        endıspanel = new javax.swing.JPanel();
        usermanagement = new javax.swing.JPanel();
        tableuser = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        delete_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        display_button = new javax.swing.JButton();
        user_process = new javax.swing.JLabel();
        searchtf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        eventmanegement = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        srcev = new javax.swing.JTextField();
        labelevent = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        rbadd = new javax.swing.JRadioButton();
        rbupdate = new javax.swing.JRadioButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        update = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        pancity = new javax.swing.JPanel();
        city = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        pandate = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        eventdate = new datechooser.beans.DateChooserCombo();
        loc = new javax.swing.JCheckBox();
        cbdate = new javax.swing.JCheckBox();
        add = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        event_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        eventloc = new javax.swing.JComboBox<>();
        addlb = new javax.swing.JLabel();
        date = new datechooser.beans.DateChooserCombo();
        delete_button1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        info = new javax.swing.JPanel();
        badmin1 = new javax.swing.JButton();
        tarequest = new javax.swing.JLabel();
        totaluser = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        ga = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        bsend = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Panel");
        setUndecorated(true);

        admin.setBackground(new java.awt.Color(255, 102, 102));
        admin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        admin.setPreferredSize(new java.awt.Dimension(1054, 828));
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });

        endıspanel.setBackground(new java.awt.Color(29, 23, 23));
        endıspanel.setPreferredSize(new java.awt.Dimension(1054, 828));

        usermanagement.setBackground(new java.awt.Color(0, 0, 102));
        usermanagement.setPreferredSize(new java.awt.Dimension(1054, 828));
        usermanagement.setLayout(null);

        usertable.setBackground(new java.awt.Color(204, 204, 204));
        usertable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account Id", "Username", "Name", "Surname", "City", "Gender", "E-mail", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableuser.setViewportView(usertable);
        if (usertable.getColumnModel().getColumnCount() > 0) {
            usertable.getColumnModel().getColumn(0).setResizable(false);
            usertable.getColumnModel().getColumn(1).setResizable(false);
            usertable.getColumnModel().getColumn(2).setResizable(false);
            usertable.getColumnModel().getColumn(3).setResizable(false);
            usertable.getColumnModel().getColumn(4).setResizable(false);
            usertable.getColumnModel().getColumn(5).setResizable(false);
            usertable.getColumnModel().getColumn(6).setResizable(false);
            usertable.getColumnModel().getColumn(7).setResizable(false);
        }

        usermanagement.add(tableuser);
        tableuser.setBounds(370, 240, 660, 520);

        jPanel2.setBackground(new java.awt.Color(6, 36, 61));

        delete_button.setBackground(new java.awt.Color(6, 36, 61));
        delete_button.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        delete_button.setForeground(new java.awt.Color(255, 255, 255));
        delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/delete1.png"))); // NOI18N
        delete_button.setText("  DELETE USER");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));

        display_button.setBackground(new java.awt.Color(6, 36, 61));
        display_button.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        display_button.setForeground(new java.awt.Color(255, 255, 255));
        display_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/show.png"))); // NOI18N
        display_button.setText("  DISPLAY USER");
        display_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_buttonActionPerformed(evt);
            }
        });

        user_process.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        user_process.setForeground(new java.awt.Color(255, 255, 255));
        user_process.setText("User Process ....");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(display_button, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user_process, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(user_process, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(display_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(361, 361, 361))))
        );

        usermanagement.add(jPanel2);
        jPanel2.setBounds(-10, 0, 340, 830);

        searchtf.setForeground(new java.awt.Color(153, 153, 153));
        searchtf.setText("SEARCH USER..");
        searchtf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchtfMouseClicked(evt);
            }
        });
        searchtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtfActionPerformed(evt);
            }
        });
        searchtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtfKeyReleased(evt);
            }
        });
        usermanagement.add(searchtf);
        searchtf.setBounds(730, 30, 290, 41);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/search.png"))); // NOI18N
        usermanagement.add(jLabel1);
        jLabel1.setBounds(630, 20, 410, 60);

        jPanel4.setBackground(new java.awt.Color(6, 36, 61));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        usermanagement.add(jPanel4);
        jPanel4.setBounds(340, 0, 710, 190);

        javax.swing.GroupLayout endıspanelLayout = new javax.swing.GroupLayout(endıspanel);
        endıspanel.setLayout(endıspanelLayout);
        endıspanelLayout.setHorizontalGroup(
            endıspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endıspanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usermanagement, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
                .addContainerGap())
        );
        endıspanelLayout.setVerticalGroup(
            endıspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endıspanelLayout.createSequentialGroup()
                .addComponent(usermanagement, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        admin.addTab("User Management", endıspanel);

        eventmanegement.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(6, 36, 61));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/search.png"))); // NOI18N

        srcev.setForeground(new java.awt.Color(204, 204, 204));
        srcev.setText("SEARCH EVENT");
        srcev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                srcevMouseClicked(evt);
            }
        });
        srcev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcevActionPerformed(evt);
            }
        });
        srcev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srcevKeyReleased(evt);
            }
        });

        labelevent.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        labelevent.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(srcev, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(labelevent, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(srcev, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(labelevent, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(6, 36, 61));

        rbadd.setBackground(new java.awt.Color(6, 36, 61));
        buttonGroup1.add(rbadd);
        rbadd.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        rbadd.setForeground(new java.awt.Color(255, 255, 255));
        rbadd.setText("ADD");
        rbadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbaddActionPerformed(evt);
            }
        });

        rbupdate.setBackground(new java.awt.Color(6, 36, 61));
        buttonGroup1.add(rbupdate);
        rbupdate.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        rbupdate.setForeground(new java.awt.Color(255, 255, 255));
        rbupdate.setText("UPDATE");
        rbupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbupdateActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update.setBackground(new java.awt.Color(6, 36, 61));
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButton3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        city.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rize", "İstanbul", "Ankara", "İzmir", "Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Aksaray", "Amasya", "Antalya", "Ardahan", "Artvin", "Aydın", "Balıkesir", "Bartın", "Batman", "Bayburt", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Düzce", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkari", "Hatay", "Iğdır", "Isparta", "Kahramanmaraş", "Karabük", "Karaman", "Kars", "Kastamonu", "Kayseri", "Kırıkkale", "Kırklareli", "Kırşehir", "Kilis", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Mardin", "Mersin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Osmaniye", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Şırnak", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Şanlıurfa", "Uşak", "Van", "Yalova", "Yozgat", "Zonguldak" }));
        city.setSelectedIndex(-1);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText("City:");

        javax.swing.GroupLayout pancityLayout = new javax.swing.GroupLayout(pancity);
        pancity.setLayout(pancityLayout);
        pancityLayout.setHorizontalGroup(
            pancityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pancityLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pancityLayout.setVerticalGroup(
            pancityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pancityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pancityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Event Date:");

        eventdate.setCurrentView(new datechooser.view.appearance.AppearancesList("Dali",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    try {
        eventdate.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    try {
        eventdate.setForbiddenPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }

    javax.swing.GroupLayout pandateLayout = new javax.swing.GroupLayout(pandate);
    pandate.setLayout(pandateLayout);
    pandateLayout.setHorizontalGroup(
        pandateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pandateLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(eventdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    pandateLayout.setVerticalGroup(
        pandateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pandateLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pandateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(eventdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pandateLayout.createSequentialGroup()
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
            .addContainerGap())
    );

    loc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    loc.setForeground(new java.awt.Color(255, 255, 255));
    loc.setText("Update Location");
    loc.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            locActionPerformed(evt);
        }
    });

    cbdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    cbdate.setForeground(new java.awt.Color(255, 255, 255));
    cbdate.setText("Update Date");
    cbdate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cbdateActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout updateLayout = new javax.swing.GroupLayout(update);
    update.setLayout(updateLayout);
    updateLayout.setHorizontalGroup(
        updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(95, 95, 95))
        .addGroup(updateLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pancity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pandate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(updateLayout.createSequentialGroup()
                    .addComponent(loc)
                    .addGap(64, 64, 64)
                    .addComponent(cbdate)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    updateLayout.setVerticalGroup(
        updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(updateLayout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(loc)
                .addComponent(cbdate))
            .addGap(27, 27, 27)
            .addComponent(pancity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(32, 32, 32)
            .addComponent(pandate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(74, 74, 74))
    );

    jLayeredPane2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 7, 340, 420));

    add.setBackground(new java.awt.Color(6, 36, 61));
    add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

    jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Event Name:");

    jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Event Date:");

    jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(255, 255, 255));
    jLabel11.setText("Event Location:");

    jButton2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
    jButton2.setForeground(new java.awt.Color(255, 255, 255));
    jButton2.setText("ADD");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    eventloc.setBackground(new java.awt.Color(6, 36, 61));
    eventloc.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
    eventloc.setForeground(new java.awt.Color(255, 255, 255));
    eventloc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İstanbul", "Ankara", "İzmir", "Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Aksaray", "Amasya", "Antalya", "Ardahan", "Artvin", "Aydın", "Balıkesir", "Bartın", "Batman", "Bayburt", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Düzce", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkari", "Hatay", "Iğdır", "Isparta", "Kahramanmaraş", "Karabük", "Karaman", "Kars", "Kastamonu", "Kayseri", "Kırıkkale", "Kırklareli", "Kırşehir", "Kilis", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Mardin", "Mersin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Osmaniye", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Şırnak", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Şanlıurfa", "Uşak", "Van", "Yalova", "Yozgat", "Zonguldak" }));
    eventloc.setSelectedIndex(-1);
    eventloc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
    eventloc.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            eventlocActionPerformed(evt);
        }
    });
    eventloc.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            eventlocKeyPressed(evt);
        }
    });

    addlb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    addlb.setForeground(new java.awt.Color(255, 255, 255));

    date.setCurrentView(new datechooser.view.appearance.AppearancesList("Dali",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
try {
    date.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }

    javax.swing.GroupLayout addLayout = new javax.swing.GroupLayout(add);
    add.setLayout(addLayout);
    addLayout.setHorizontalGroup(
        addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
        .addGroup(addLayout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(addlb, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(addLayout.createSequentialGroup()
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(addLayout.createSequentialGroup()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(event_name, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(addLayout.createSequentialGroup()
                    .addComponent(jLabel11)
                    .addGap(18, 18, 18)
                    .addComponent(eventloc, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(14, Short.MAX_VALUE))
    );
    addLayout.setVerticalGroup(
        addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(addLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(addlb, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(28, 28, 28)
            .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(event_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(eventloc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(45, 45, 45)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(88, Short.MAX_VALUE))
    );

    jLayeredPane2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, -1));

    delete_button1.setBackground(new java.awt.Color(6, 36, 61));
    delete_button1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
    delete_button1.setForeground(new java.awt.Color(255, 255, 255));
    delete_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/delete1.png"))); // NOI18N
    delete_button1.setText(" DELETE EVENT");
    delete_button1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            delete_button1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
            .addGap(59, 59, 59)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(rbadd, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)
                    .addComponent(rbupdate)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(delete_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(51, 51, 51))
    );
    jPanel8Layout.setVerticalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
            .addGap(81, 81, 81)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbadd)
                .addComponent(rbupdate))
            .addGap(18, 18, 18)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(95, 95, 95)
            .addComponent(delete_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(159, Short.MAX_VALUE))
    );

    table.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Event Id", "Event Name", "Event Location", "Event Date"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false, false
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    jScrollPane2.setViewportView(table);
    if (table.getColumnModel().getColumnCount() > 0) {
        table.getColumnModel().getColumn(0).setResizable(false);
        table.getColumnModel().getColumn(1).setResizable(false);
        table.getColumnModel().getColumn(2).setResizable(false);
        table.getColumnModel().getColumn(3).setResizable(false);
    }

    javax.swing.GroupLayout eventmanegementLayout = new javax.swing.GroupLayout(eventmanegement);
    eventmanegement.setLayout(eventmanegementLayout);
    eventmanegementLayout.setHorizontalGroup(
        eventmanegementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eventmanegementLayout.createSequentialGroup()
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(eventmanegementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2)))
    );
    eventmanegementLayout.setVerticalGroup(
        eventmanegementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(eventmanegementLayout.createSequentialGroup()
            .addGroup(eventmanegementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(eventmanegementLayout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    admin.addTab("Event Management", eventmanegement);

    info.setBackground(new java.awt.Color(6, 36, 61));

    badmin1.setBackground(new java.awt.Color(51, 255, 0));
    badmin1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    badmin1.setText("Accept All Request");
    badmin1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            badmin1ActionPerformed(evt);
        }
    });

    tarequest.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    tarequest.setForeground(new java.awt.Color(255, 255, 255));
    tarequest.setText("*");

    totaluser.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    totaluser.setForeground(new java.awt.Color(255, 255, 255));
    totaluser.setText("*");

    age.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    age.setForeground(new java.awt.Color(255, 255, 255));
    age.setText("*");

    logout.setBackground(new java.awt.Color(204, 0, 0));
    logout.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    logout.setText("Log Out");
    logout.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logoutActionPerformed(evt);
        }
    });

    ga.setBackground(new java.awt.Color(255, 204, 204));
    ga.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    ga.setText("Make an Announcement");
    ga.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            gaActionPerformed(evt);
        }
    });

    ta.setColumns(20);
    ta.setRows(5);
    jScrollPane1.setViewportView(ta);

    bsend.setBackground(new java.awt.Color(102, 255, 102));
    bsend.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    bsend.setText("Send");
    bsend.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bsendActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
    info.setLayout(infoLayout);
    infoLayout.setHorizontalGroup(
        infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(infoLayout.createSequentialGroup()
                    .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(totaluser, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                    .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bsend, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(infoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(80, 80, 80))
        .addGroup(infoLayout.createSequentialGroup()
            .addGap(39, 39, 39)
            .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(infoLayout.createSequentialGroup()
                    .addComponent(tarequest, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(infoLayout.createSequentialGroup()
                    .addComponent(badmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ga, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(160, 160, 160))))
    );
    infoLayout.setVerticalGroup(
        infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(infoLayout.createSequentialGroup()
            .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(infoLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                    .addContainerGap(81, Short.MAX_VALUE)
                    .addComponent(tarequest, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)))
            .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(ga, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(badmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                    .addGap(18, 18, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(bsend, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5))
                .addGroup(infoLayout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addComponent(totaluser, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(61, 61, 61)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap(105, Short.MAX_VALUE))
    );

    admin.addTab("Info", info);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(admin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
         model=(DefaultTableModel) table.getModel();
        
          
            int size=Admin.getMyEvent().size();
            int row_count=table.getRowCount();
        
         
             for (int i = 0; i < size; i++) {
                 
                  if(row_count<size){
                 Object [] a={Admin.getMyEvent().get(i).getEvent_id(),Admin.getMyEvent().get(i).getEvent_name(),Admin.getMyEvent().get(i).getLocation(),Admin.getMyEvent().get(i).getCalendartoString()};
                 model.addRow(a);
                  }
             row_count++;
         
         }
        
       tarequest.setText("Pending request : "+UserInfo.getMyParticipants().size());
        totaluser.setText("Total user :"+UserInfo.getMyusers().size());
        
        age.setText("Average age of users :"+Users.averageAge());
        
        
    }//GEN-LAST:event_adminMouseClicked

    private void delete_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_button1ActionPerformed
         int selected_row=table.getSelectedRow();

        if(Admin.getMyEvent().isEmpty())
        labelevent.setText("There is no event to delete !");
        else{
            if(selected_row==-1)
            labelevent.setText("Select a row to delete event !");

            if(!Admin.getMyEvent().isEmpty() &&selected_row!=-1)
            {
                int id =(int) table.getValueAt(selected_row, 0);
              
                Admin.removeEvent(id);
                model.removeRow(selected_row);
                UserInfo.writeToEventforUpdate ();
                labelevent.setText("Event is deleted succesfully !");

            }
        }
 
    }//GEN-LAST:event_delete_button1ActionPerformed

    private void rbupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbupdateActionPerformed
        update.setVisible(true);
        add.setVisible(false);
    }//GEN-LAST:event_rbupdateActionPerformed

    private void rbaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbaddActionPerformed
        add.setVisible(true);
        update.setVisible(false);
    }//GEN-LAST:event_rbaddActionPerformed

    private void srcevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcevActionPerformed

    private void srcevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srcevMouseClicked
        srcev.setText("");
    }//GEN-LAST:event_srcevMouseClicked

    private void searchtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtfKeyReleased
        String search=searchtf.getText();
        dinamicSearchforUser(search);
    }//GEN-LAST:event_searchtfKeyReleased

    private void searchtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtfActionPerformed

    private void searchtfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchtfMouseClicked
        searchtf.setText("");
    }//GEN-LAST:event_searchtfMouseClicked

    private void display_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_buttonActionPerformed
        tableuser.setVisible(true);

        model2=(DefaultTableModel) usertable.getModel();

        if(UserInfo.getMyusers().isEmpty())
        user_process.setText("There is no user to display !");
        else{

            int size=UserInfo.getMyusers().size();
            int row_count=usertable.getRowCount();

            for (int h = 0; h < size; h++) {

                if(row_count<size){
                    Object [] a={UserInfo.getMyusers().get(h).getAccount_id(),
                        UserInfo.getMyusers().get(h).getUsername(),
                        UserInfo.getMyusers().get(h).getUser().getUser_name(),
                        UserInfo.getMyusers().get(h).getUser().getUser_sur(),
                        UserInfo.getMyusers().get(h).getUser().getCity(),
                        UserInfo.getMyusers().get(h).getUser().getGender(),
                        UserInfo.getMyusers().get(h).getUser().getEmail(),
                        UserInfo.getMyusers().get(h).getUser().getUser_age()};
                    model2.addRow(a);
                }
                row_count++;

            }

        }
    }//GEN-LAST:event_display_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        //remove item from delete and search combobox
        int selected_row=usertable.getSelectedRow();

        if (!UserInfo.getMyusers().isEmpty() ) {

            if(selected_row==-1)
            user_process.setText("Select a row to delete user !");
            else{

                int id=(int) usertable.getValueAt(selected_row, 0);
                model2.removeRow(selected_row);
                UserInfo.delete(id);//delete user from arraylist
                UserInfo.writeUserToUserforUpdate();//delete user from txt
                user_process.setText("User is deleted !! ");

            }

        }
        else
        user_process.setText("There is no user to delete !");
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void badmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badmin1ActionPerformed
        
        if(UserInfo.getMyParticipants().isEmpty())
        tarequest.setText("There is no request !");
        else{
             
             
             
            for (int j = 0; j < UserInfo.getMyParticipants().size(); j++) {
                String Icerik="Registration is approved :) Welcome "+UserInfo.getMyParticipants().get(j).getUser().getUser_name();
            }
           
            tarequest.setText("Accepted all request !");
            totaluser.setText("Total user :"+UserInfo.getMyusers().size());
        
        age.setText("Average age of users :"+Users.averageAge());
            UserInfo.AcceptRequest();
        }
    }//GEN-LAST:event_badmin1ActionPerformed

    private void eventlocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventlocActionPerformed

    }//GEN-LAST:event_eventlocActionPerformed

    private void eventlocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eventlocKeyPressed

    }//GEN-LAST:event_eventlocKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            String eventname=event_name.getText();
            String eventlocation=(String)eventloc.getSelectedItem();
            Calendar dt=date.getSelectedDate();

            if(eventname.isEmpty())
                addlb.setText("Enter an event name !");
            if(eventloc.getSelectedIndex()==-1)
                addlb.setText("Select a city !");
         
            if(!(eventname.isEmpty() && eventlocation.isEmpty()))
            {
            
            SimpleDateFormat format1 = new SimpleDateFormat("dd.MM.yyyy");
            String formatted = format1.format(dt.getTime());

            Event e=new Event(eventname, eventlocation, dt);
            Admin.addEvent(e);
            
            writeToEvent(e.getEvent_id(),eventname,eventlocation,dt);
            
           

          i= Admin.getMyEvent().size() -1 ;
          

            Object [] add_object={Admin.getMyEvent().get(i).getEvent_id(),Admin.getMyEvent().get(i).getEvent_name(),Admin.getMyEvent().get(i).getLocation(),formatted};
            model.addRow(add_object);
            i++;

            labelevent.setText("Event is added succesfully !!");

          
        add.setVisible(false);
        update.setVisible(false);
        cbdate.setSelected(false);
        loc.setSelected(false);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        int selected_row=table.getSelectedRow();

        if(Admin.getMyEvent().isEmpty()){
            labelevent.setText("There is no event to update !");
            update.setVisible(false);
            rbupdate.setSelected(false);
            cbdate.setSelected(false);
            loc.setSelected(false);
        }
        if(!Admin.getMyEvent().isEmpty())
        {
            if(loc.isSelected())
            {
                loc.setSelected(true);
                String location=(String) city.getSelectedItem();

                if(selected_row==-1)
                labelevent.setText("Select a row to update !!");
                else
                {

                       int id=(int) table.getValueAt(selected_row, 0);
                
             
                   
                       if(Admin.updateCity(location,id))     //update in array
                        labelevent.setText("Event location is updated !");
                       else
                        labelevent.setText("Event location could not updated !");
                       
                       UserInfo.writeToEventforUpdate ();//update location in event txt
                       model.setValueAt(location, selected_row, 2);//update in table
                    update.setVisible(false);
                    rbupdate.setSelected(false);

                }

            }

            if(cbdate.isSelected())
            {

                cbdate.setSelected(true);
                Calendar date_event=eventdate.getSelectedDate();

                

                if(selected_row==-1)
                labelevent.setText("Select a row to update !!");
                else{

                    
                    int id=(int) table.getValueAt(selected_row, 0);
                    
                    if(Admin.updateDate(date_event,id ))
                    {
                     SimpleDateFormat format1 = new SimpleDateFormat("dd.MM.yyyy");
                     String formatted = format1.format(date_event.getTime());
                     labelevent.setText("Event date is updated !!");
                     UserInfo.writeToEventforUpdate ();//update date in event txt
                     model.setValueAt(formatted, selected_row, 3);//update in table
                    }
                    else
                     labelevent.setText("Event date could not updated !");   
                     
                   
                    update.setVisible(false);
                   
                    rbupdate.setSelected(false);
                    
                }

            }

            if(cbdate.isSelected() && loc.isSelected())
            {

                cbdate.setSelected(true);
                loc.setSelected(true);

                String location=(String) city.getSelectedItem();
                Calendar date_event=eventdate.getSelectedDate();

                SimpleDateFormat format1 = new SimpleDateFormat("dd.MM.yyyy");
                String formatted = format1.format(date_event.getTime());

                if(selected_row==-1)
                labelevent.setText("Select a row to update !!");
                else{
                    
                    
                    int id=(int) table.getValueAt(selected_row, 0);
                
             
                   
                       if(Admin.updateCity(location, id) && Admin.updateDate(date_event,id ))     //update in array
                        labelevent.setText("Event location and date are updated !");
                       else
                        labelevent.setText("Event location and date could not updated !");
                  
                    
                    UserInfo.writeToEventforUpdate ();//update location in event txt
                    model.setValueAt(location, selected_row, 2);
                    model.setValueAt(formatted, selected_row, 3);
                   
                   
                    rbupdate.setSelected(false);
                    update.setVisible(false);
                    labelevent.setText("Event date and location is updated !!");

                }

            }

            if(!cbdate.isSelected() && !loc.isSelected())
            labelevent.setText("You should select update version !! ");

        }

        table.clearSelection();
       add.setVisible(false);
       update.setVisible(false);
                
        loc.setSelected(false);
        cbdate.setSelected(false);
        rbadd.setSelected(false);
        add.setVisible(false);
        rbupdate.setSelected(false);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        setVisible(false);
        Welcomepage a=new Welcomepage();
        a.setVisible(true);

    }//GEN-LAST:event_logoutActionPerformed

    private void locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locActionPerformed
      if(loc.isSelected())
      {
           pancity.setVisible(true);
     
      }
      else
          pancity.setVisible(false);
         
    }//GEN-LAST:event_locActionPerformed

    private void cbdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdateActionPerformed
      if(cbdate.isSelected())
      {
           pandate.setVisible(true);
     
      }
      else
          pandate.setVisible(false);
    }//GEN-LAST:event_cbdateActionPerformed

    private void srcevKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srcevKeyReleased
      
        String search=srcev.getText();
        dinamicSearch(search);
    }//GEN-LAST:event_srcevKeyReleased

    private void bsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsendActionPerformed
      ta.setVisible(false);
      bsend.setVisible(false);
     
    }//GEN-LAST:event_bsendActionPerformed

    private void gaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaActionPerformed
        if(ta.isShowing())
        {
            ta.setVisible(false);
            bsend.setVisible(false);

        }
        else{
            bsend.setVisible(true);
            ta.setVisible(true);
        }
    }//GEN-LAST:event_gaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Panel().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.JLabel addlb;
    private javax.swing.JTabbedPane admin;
    private javax.swing.JLabel age;
    private javax.swing.JButton badmin1;
    private javax.swing.JButton bsend;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbdate;
    private javax.swing.JComboBox city;
    private datechooser.beans.DateChooserCombo date;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton delete_button1;
    private javax.swing.JButton display_button;
    private javax.swing.JPanel endıspanel;
    private javax.swing.JTextField event_name;
    private datechooser.beans.DateChooserCombo eventdate;
    private javax.swing.JComboBox<String> eventloc;
    private javax.swing.JPanel eventmanegement;
    private javax.swing.JButton ga;
    private javax.swing.JPanel info;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelevent;
    private javax.swing.JCheckBox loc;
    private javax.swing.JButton logout;
    private javax.swing.JPanel pancity;
    private javax.swing.JPanel pandate;
    private javax.swing.JRadioButton rbadd;
    private javax.swing.JRadioButton rbupdate;
    private javax.swing.JTextField searchtf;
    private javax.swing.JTextField srcev;
    public static javax.swing.JTextArea ta;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableuser;
    private javax.swing.JLabel tarequest;
    private javax.swing.JLabel totaluser;
    private javax.swing.JPanel update;
    private javax.swing.JLabel user_process;
    private javax.swing.JPanel usermanagement;
    private javax.swing.JTable usertable;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("adminpanelicon.jpg")));
        
    }

}
