/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Account;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Özkan
 */
public class Welcomepage extends javax.swing.JFrame {

    /**
     * Creates new form newFrame
     */
    public Welcomepage() {
        initComponents();
        PanelUser.setVisible(false);
        PanelAdmin.setVisible(false);
       
        
     aboutuspan.setVisible(false);
        PanelRegister.setVisible(false);
        concactuspan.setVisible(false);
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        adminlb = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        userlb = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        PanelUser = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        userloginb = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        lbwelcome = new javax.swing.JLabel();
        PanelAdmin = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        username_admin = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        password_admin = new javax.swing.JPasswordField();
        jButton8 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        PanelRegister = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        username_user = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        password_user = new javax.swing.JPasswordField();
        jLabel28 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        citycombox = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        gendercombobox = new javax.swing.JComboBox();
        submitbutton = new javax.swing.JButton();
        lb = new javax.swing.JLabel();
        lbuser = new javax.swing.JLabel();
        passlabel = new javax.swing.JLabel();
        Name_L = new javax.swing.JLabel();
        Last_L = new javax.swing.JLabel();
        mail_L = new javax.swing.JLabel();
        City_L = new javax.swing.JLabel();
        gender_L = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        aboutuspan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        concactuspan = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        welcompanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(6, 36, 61));
        jPanel4.setMinimumSize(new java.awt.Dimension(500, 480));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER LOGIN");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username:");

        jTextField1.setBackground(new java.awt.Color(6, 36, 61));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password:");

        jPasswordField1.setBackground(new java.awt.Color(6, 36, 61));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jButton4.setText("Cancel");

        jButton3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("X");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel10))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(187, 187, 187)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(101, 101, 101)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10)))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-a-64.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 204));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(6, 36, 61));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-server-50.png"))); // NOI18N
        jLabel4.setText("Peak Event");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 50));

        adminlb.setBackground(new java.awt.Color(255, 204, 204));
        adminlb.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        adminlb.setForeground(new java.awt.Color(255, 255, 255));
        adminlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-admin-settings-male-64.png"))); // NOI18N
        adminlb.setText(" ADMIN LOGIN");
        adminlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminlbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminlbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminlbMouseExited(evt);
            }
        });
        jPanel1.add(adminlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 240, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 300, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-contact-64.png"))); // NOI18N
        jLabel7.setText("CONTACT US");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jLabel7.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jLabel7ComponentMoved(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 230, 50));

        userlb.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        userlb.setForeground(new java.awt.Color(255, 255, 255));
        userlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-user-64.png"))); // NOI18N
        userlb.setText(" USER LOGIN");
        userlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userlbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userlbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userlbMouseExited(evt);
            }
        });
        jPanel1.add(userlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 220, 50));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-cash-register-64.png"))); // NOI18N
        jLabel16.setText("  REGISTER");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 220, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 302, 862));

        jPanel3.setBackground(new java.awt.Color(6, 36, 61));

        txtExit.setBackground(new java.awt.Color(255, 51, 51));
        txtExit.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        txtExit.setForeground(new java.awt.Color(255, 255, 255));
        txtExit.setText("X");
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/welcomgif.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(txtExit)
                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 780, 180));

        PanelUser.setBackground(new java.awt.Color(6, 36, 61));
        PanelUser.setMinimumSize(new java.awt.Dimension(500, 480));
        PanelUser.setPreferredSize(new java.awt.Dimension(800, 970));
        PanelUser.setRequestFocusEnabled(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Username:");

        username.setBackground(new java.awt.Color(6, 36, 61));
        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Password:");

        password.setBackground(new java.awt.Color(6, 36, 61));
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        userloginb.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        userloginb.setText("Login");
        userloginb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userloginbActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Semilight", 0, 40)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-user-64.png"))); // NOI18N

        lbwelcome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbwelcome.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelUserLayout = new javax.swing.GroupLayout(PanelUser);
        PanelUser.setLayout(PanelUserLayout);
        PanelUserLayout.setHorizontalGroup(
            PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(PanelUserLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelUserLayout.createSequentialGroup()
                                .addGroup(PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelUserLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(userloginb, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(101, Short.MAX_VALUE))))
            .addGroup(PanelUserLayout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelUserLayout.setVerticalGroup(
            PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(79, 79, 79)
                .addComponent(userloginb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lbwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(388, Short.MAX_VALUE))
        );

        PanelAdmin.setBackground(new java.awt.Color(6, 36, 61));
        PanelAdmin.setMinimumSize(new java.awt.Dimension(500, 480));
        PanelAdmin.setPreferredSize(new java.awt.Dimension(800, 970));
        PanelAdmin.setRequestFocusEnabled(false);

        jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Username:");

        username_admin.setBackground(new java.awt.Color(6, 36, 61));
        username_admin.setForeground(new java.awt.Color(255, 255, 255));
        username_admin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        username_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_adminActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Password:");

        password_admin.setBackground(new java.awt.Color(6, 36, 61));
        password_admin.setForeground(new java.awt.Color(255, 255, 255));
        password_admin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        password_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_adminActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jButton8.setText("Login");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-admin-settings-male-64.png"))); // NOI18N

        javax.swing.GroupLayout PanelAdminLayout = new javax.swing.GroupLayout(PanelAdmin);
        PanelAdmin.setLayout(PanelAdminLayout);
        PanelAdminLayout.setHorizontalGroup(
            PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminLayout.createSequentialGroup()
                .addComponent(jSeparator6)
                .addGap(111, 111, 111))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
            .addGroup(PanelAdminLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(54, 54, 54)
                .addGroup(PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(337, 337, 337))
        );
        PanelAdminLayout.setVerticalGroup(
            PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(password_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );

        PanelRegister.setBackground(new java.awt.Color(6, 36, 61));
        PanelRegister.setPreferredSize(new java.awt.Dimension(800, 970));
        PanelRegister.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Segoe UI Semilight", 0, 40)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("REGISTER FORM");
        PanelRegister.add(jLabel17);
        jLabel17.setBounds(240, 0, 370, 90);

        jLabel20.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("First Name:");
        PanelRegister.add(jLabel20);
        jLabel20.setBounds(170, 170, 120, 30);

        first_name.setBackground(new java.awt.Color(6, 36, 61));
        first_name.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        first_name.setForeground(new java.awt.Color(255, 255, 255));
        first_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        PanelRegister.add(first_name);
        first_name.setBounds(320, 170, 200, 30);

        jLabel25.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Last Name:");
        PanelRegister.add(jLabel25);
        jLabel25.setBounds(170, 220, 110, 30);

        last_name.setBackground(new java.awt.Color(6, 36, 61));
        last_name.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        last_name.setForeground(new java.awt.Color(255, 255, 255));
        last_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        PanelRegister.add(last_name);
        last_name.setBounds(320, 220, 200, 30);

        jLabel26.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Username:");
        PanelRegister.add(jLabel26);
        jLabel26.setBounds(170, 270, 110, 30);

        username_user.setBackground(new java.awt.Color(6, 36, 61));
        username_user.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        username_user.setForeground(new java.awt.Color(255, 255, 255));
        username_user.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        PanelRegister.add(username_user);
        username_user.setBounds(320, 270, 200, 30);

        jLabel27.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Password:");
        PanelRegister.add(jLabel27);
        jLabel27.setBounds(170, 320, 110, 30);

        password_user.setBackground(new java.awt.Color(6, 36, 61));
        password_user.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        password_user.setForeground(new java.awt.Color(255, 255, 255));
        password_user.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        PanelRegister.add(password_user);
        password_user.setBounds(320, 320, 200, 30);

        jLabel28.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("E-mail:");
        PanelRegister.add(jLabel28);
        jLabel28.setBounds(170, 370, 90, 30);

        email.setBackground(new java.awt.Color(6, 36, 61));
        email.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        PanelRegister.add(email);
        email.setBounds(320, 370, 200, 30);

        jLabel29.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Age :");
        PanelRegister.add(jLabel29);
        jLabel29.setBounds(170, 420, 50, 30);

        age.setBackground(new java.awt.Color(6, 36, 61));
        age.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        PanelRegister.add(age);
        age.setBounds(320, 420, 200, 30);

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Gender:");
        PanelRegister.add(jLabel30);
        jLabel30.setBounds(170, 520, 90, 30);

        citycombox.setBackground(new java.awt.Color(6, 36, 61));
        citycombox.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        citycombox.setForeground(new java.awt.Color(255, 255, 255));
        citycombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İstanbul", "Ankara", "İzmir", "Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Aksaray", "Amasya", "Antalya", "Ardahan", "Artvin", "Aydın", "Balıkesir", "Bartın", "Batman", "Bayburt", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Düzce", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkari", "Hatay", "Iğdır", "Isparta", "Kahramanmaraş", "Karabük", "Karaman", "Kars", "Kastamonu", "Kayseri", "Kırıkkale", "Kırklareli", "Kırşehir", "Kilis", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Mardin", "Mersin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Osmaniye", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Şırnak", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Şanlıurfa", "Uşak", "Van", "Yalova", "Yozgat", "Zonguldak" }));
        citycombox.setSelectedIndex(-1);
        citycombox.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        citycombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citycomboxActionPerformed(evt);
            }
        });
        citycombox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                citycomboxKeyPressed(evt);
            }
        });
        PanelRegister.add(citycombox);
        citycombox.setBounds(320, 470, 200, 30);

        jLabel31.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("City: ");
        PanelRegister.add(jLabel31);
        jLabel31.setBounds(170, 470, 50, 30);

        gendercombobox.setBackground(new java.awt.Color(6, 36, 61));
        gendercombobox.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        gendercombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Female", "Male", " " }));
        gendercombobox.setSelectedIndex(-1);
        PanelRegister.add(gendercombobox);
        gendercombobox.setBounds(320, 520, 200, 30);

        submitbutton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });
        PanelRegister.add(submitbutton);
        submitbutton.setBounds(250, 590, 310, 31);

        lb.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb.setForeground(new java.awt.Color(255, 0, 0));
        PanelRegister.add(lb);
        lb.setBounds(550, 420, 210, 30);

        lbuser.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbuser.setForeground(new java.awt.Color(255, 0, 0));
        PanelRegister.add(lbuser);
        lbuser.setBounds(540, 270, 250, 30);

        passlabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        passlabel.setForeground(new java.awt.Color(255, 0, 51));
        PanelRegister.add(passlabel);
        passlabel.setBounds(530, 320, 270, 30);

        Name_L.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Name_L.setForeground(new java.awt.Color(255, 51, 51));
        PanelRegister.add(Name_L);
        Name_L.setBounds(540, 170, 260, 30);

        Last_L.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Last_L.setForeground(new java.awt.Color(255, 51, 51));
        PanelRegister.add(Last_L);
        Last_L.setBounds(550, 220, 240, 30);

        mail_L.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        mail_L.setForeground(new java.awt.Color(255, 0, 0));
        PanelRegister.add(mail_L);
        mail_L.setBounds(540, 370, 260, 30);

        City_L.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        City_L.setForeground(new java.awt.Color(255, 0, 0));
        PanelRegister.add(City_L);
        City_L.setBounds(550, 470, 250, 30);

        gender_L.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        gender_L.setForeground(new java.awt.Color(255, 0, 51));
        PanelRegister.add(gender_L);
        gender_L.setBounds(550, 520, 240, 30);

        info.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        info.setForeground(new java.awt.Color(255, 255, 255));
        info.setText("* FILL THE ALL BLANKS !!");
        PanelRegister.add(info);
        info.setBounds(10, 100, 410, 30);

        jLabel32.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(6, 36, 61));
        jLabel32.setPreferredSize(new java.awt.Dimension(800, 700));
        PanelRegister.add(jLabel32);
        jLabel32.setBounds(0, 0, 800, 700);
        PanelRegister.add(jSeparator5);
        jSeparator5.setBounds(0, 90, 810, 2);

        aboutuspan.setBackground(new java.awt.Color(6, 36, 61));
        aboutuspan.setPreferredSize(new java.awt.Dimension(800, 970));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/event2.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel40.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 255, 204));
        jLabel40.setText("PEAK EVENT CREATES OPPORTUNITIES");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Peak event is a platform for finding and creating local communities.");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("People use us for finding new friends, learning new things ,finding support,push one’s own limits  and ");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("going after their passion alltogether.");

        jLabel44.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(51, 255, 204));
        jLabel44.setText("THINGS THAT YOU CAN DO ");

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-city-64.png"))); // NOI18N
        jLabel45.setText("DISCOVER YOUR CİTY");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-brief-64.png"))); // NOI18N
        jLabel46.setText("CREATE A CAREER FOR YOURSELF");

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-idea-64.png"))); // NOI18N
        jLabel47.setText("BE CREATIVE");

        javax.swing.GroupLayout aboutuspanLayout = new javax.swing.GroupLayout(aboutuspan);
        aboutuspan.setLayout(aboutuspanLayout);
        aboutuspanLayout.setHorizontalGroup(
            aboutuspanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutuspanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(aboutuspanLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(aboutuspanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(aboutuspanLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jLabel46)
                        .addGap(40, 40, 40))))
            .addGroup(aboutuspanLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel44)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutuspanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(aboutuspanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutuspanLayout.createSequentialGroup()
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutuspanLayout.createSequentialGroup()
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204))))
        );
        aboutuspanLayout.setVerticalGroup(
            aboutuspanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutuspanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addGap(83, 83, 83)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(aboutuspanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane1.setLayer(PanelUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(PanelAdmin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(PanelRegister, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(aboutuspan, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(PanelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 41, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addComponent(aboutuspan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 7, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(PanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(PanelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 253, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(aboutuspan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 780, 690));

        concactuspan.setBackground(new java.awt.Color(6, 36, 61));

        jLabel33.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Instagram");
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-instagram-64.png"))); // NOI18N

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-email-100.png"))); // NOI18N

        jLabel36.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("E-mail");
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout concactuspanLayout = new javax.swing.GroupLayout(concactuspan);
        concactuspan.setLayout(concactuspanLayout);
        concactuspanLayout.setHorizontalGroup(
            concactuspanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(concactuspanLayout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        concactuspanLayout.setVerticalGroup(
            concactuspanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(concactuspanLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(concactuspanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(513, Short.MAX_VALUE))
        );

        getContentPane().add(concactuspan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 780, 680));

        welcompanel.setBackground(new java.awt.Color(102, 255, 204));
        welcompanel.setPreferredSize(new java.awt.Dimension(770, 690));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-t-64 (1).png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-p-64.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-e-64.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-a-64.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-k-64.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-e-64 (1).png"))); // NOI18N

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-v-64 (1).png"))); // NOI18N

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-e-64 (1).png"))); // NOI18N

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account/icons8-n-64 (1).png"))); // NOI18N

        javax.swing.GroupLayout welcompanelLayout = new javax.swing.GroupLayout(welcompanel);
        welcompanel.setLayout(welcompanelLayout);
        welcompanelLayout.setHorizontalGroup(
            welcompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcompanelLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(welcompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(welcompanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(welcompanelLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(welcompanelLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(welcompanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(welcompanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(welcompanelLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(welcompanelLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(welcompanelLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        welcompanelLayout.setVerticalGroup(
            welcompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcompanelLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(welcompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(welcompanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(welcompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(310, Short.MAX_VALUE))
        );

        getContentPane().add(welcompanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 780, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void userloginbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userloginbActionPerformed
        String username1 = username.getText();
        String password1 = new String(password.getPassword());
        
        if (UserInfo.control_loginUser(username1, password1)) {
            setVisible(false);
            UserPanel s = new UserPanel();
            s.setVisible(true);
            UserPanel.lbw.setText("WELCOME "+username1);
           
        }
      else if(username1.equals("") && password1.equals("")){
           JOptionPane.showMessageDialog(rootPane, "IF YOU DON'T HAVE ACCOUNT PLEASE REGISTER", "REGISTER", JOptionPane.INFORMATION_MESSAGE);
       }
       
       else if (UserInfo.control_loginParticipant(username1, password1)){
           JOptionPane.showMessageDialog(rootPane, "Your account pending admin approval", "APPLY", JOptionPane.INFORMATION_MESSAGE);
       }
       
       else{
           JOptionPane.showMessageDialog(rootPane,"USERNAME OR PASSWORD IS WRONG !!!!","ERROR!",JOptionPane.ERROR_MESSAGE);
       }
        
    }//GEN-LAST:event_userloginbActionPerformed

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked

        System.exit(0);
    }//GEN-LAST:event_txtExitMouseClicked

    private void adminlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminlbMouseClicked
      
        PanelAdmin.setVisible(true);
        PanelUser.setVisible(false);
       
        PanelRegister.setVisible(false);
        concactuspan.setVisible(false);
        
      
        
    }//GEN-LAST:event_adminlbMouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
  
    }//GEN-LAST:event_usernameActionPerformed

    private void userlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userlbMouseClicked
     
        PanelAdmin.setVisible(false);
        PanelUser.setVisible(true);
    
        PanelRegister.setVisible(false);
        
    }//GEN-LAST:event_userlbMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
      
        PanelAdmin.setVisible(false);
        PanelUser.setVisible(false);
      
      
        PanelRegister.setVisible(true);
        
    }//GEN-LAST:event_jLabel16MouseClicked

    private void citycomboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citycomboxActionPerformed

    }//GEN-LAST:event_citycomboxActionPerformed

    private void citycomboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_citycomboxKeyPressed

    }//GEN-LAST:event_citycomboxKeyPressed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed

        String name1 = first_name.getText();
        String surname1 = last_name.getText();

        String username1 = username_user.getText();
        String  pass = new String(password_user.getPassword());
        String mail1 = email.getText();
        String age1 =age.getText();
        String city1 =(String) citycombox.getSelectedItem();
        String gender1 = (String) gendercombobox.getSelectedItem();

        Participant participant1 = new Participant(username1, pass, name1, surname1, gender1, city1, mail1, age1);

        UserInfo.getMyParticipants().add(participant1);

        if(name1.isEmpty())
        {
            Name_L.setText("Name is required !!");
            UserInfo.getMyParticipants().remove(participant1);
        }
        else {

            if(surname1.isEmpty())
            {
                Last_L.setText("Lastname is required !");
                UserInfo.getMyParticipants().remove(participant1);

            }
            else{

                if( !username1.isEmpty()){
                    if(UserInfo.getMyParticipants().size()>=1){

                        if (UserInfo.controlUserName(username1)  )  {

                            UserInfo.getMyParticipants().remove(participant1);
                            lbuser.setText("* User name is already taken !");

                        }

                        else{

                            if(pass.isEmpty())
                            {
                                passlabel.setText("Password is required");
                                UserInfo.getMyParticipants().remove(participant1);

                            }
                            else{

                                if(mail1.isEmpty())
                                {
                                    mail_L.setText("Mail is required");
                                    UserInfo.getMyParticipants().remove(participant1);

                                }

                                else{
                                    if(!UserInfo.isNumeric(age1))
                                    {
                                        lb.setText("* Invalid age !");
                                        UserInfo.getMyParticipants().remove(participant1);
                                    }

                                    else{
                                        if(citycombox.getSelectedIndex()==-1)
                                        {
                                            City_L.setText("City is required");
                                            UserInfo.getMyParticipants().remove(participant1);

                                        }

                                        else{
                                            if(gendercombobox.getSelectedIndex()==-1)
                                            {
                                                gender_L.setText("Gender is required");
                                                UserInfo.getMyParticipants().remove(participant1);

                                            }
                                            else {

                                                UserInfo.writeToParticipant(name1,surname1,username1,pass,mail1,age1,city1,gender1);
                                                lbwelcome.setText("Last one step ! Wait for admin's approval :)");
                                                PanelUser.setVisible(true);
                                                PanelAdmin.setVisible(false);
                                                PanelRegister.setVisible(false);
                                                concactuspan.setVisible(false);
                                               
                                               

                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }

                    else {

                        setVisible(false);
                    }
                }
                else {
                    lbuser.setText("Username is required !");
                    UserInfo.getMyParticipants().remove(participant1);
                }

            }
        }
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
     concactuspan.setVisible(true);
        aboutuspan.setVisible(false);
        PanelAdmin.setVisible(false);
        PanelUser.setVisible(false);
   
        PanelRegister.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel7ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7ComponentMoved

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
      String internet_adresi = "https://www.instagram.com/peakeventofficial/?hl=tr";
        Desktop d = Desktop.getDesktop();
        
        try {
            d.browse(new URI(internet_adresi));
            
            /*say++;
            
            System.out.println("Butona " + say + " kere tıklandı..." );*/
        } catch (URISyntaxException ex) {
            Logger.getLogger(Welcomepage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Welcomepage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        try {
            Desktop desktop = Desktop.getDesktop();
            String message = "mailto:eventtrackingsystem@gmail.com?subject=ABOUT***&body=&attachment=c:/Update8.txt";
            URI uri = URI.create(message); 
            desktop.mail(uri);
        } catch (IOException ex) {
            Logger.getLogger(Welcomepage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        String username__admin= username_admin.getText();
        String password__admin = new String(password_admin.getPassword());

        if(UserInfo.controlAdmin(username__admin, password__admin)){
            setVisible(false);
            Admin_Panel s = new Admin_Panel();
            s.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Username or Password is Wrong","ERROR!!!!",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void password_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_adminActionPerformed

    private void username_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_adminActionPerformed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setForeground(Color.red);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(Color.white);
    }//GEN-LAST:event_jLabel4MouseExited

    private void adminlbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminlbMouseEntered
        adminlb.setForeground(Color.red);
    }//GEN-LAST:event_adminlbMouseEntered

    private void adminlbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminlbMouseExited
        adminlb.setForeground(Color.white);
    }//GEN-LAST:event_adminlbMouseExited

    private void userlbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userlbMouseEntered
        userlb.setForeground(Color.red);
    }//GEN-LAST:event_userlbMouseEntered

    private void userlbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userlbMouseExited
        userlb.setForeground(Color.white);
    }//GEN-LAST:event_userlbMouseExited

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        jLabel16.setForeground(Color.red);
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        jLabel16.setForeground(Color.white);
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setForeground(Color.red);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setForeground(Color.white);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       aboutuspan.setVisible(true);
       PanelUser.setVisible(false);
       PanelRegister.setVisible(false);
       PanelAdmin.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel City_L;
    private javax.swing.JLabel Last_L;
    private javax.swing.JLabel Name_L;
    private javax.swing.JPanel PanelAdmin;
    private javax.swing.JPanel PanelRegister;
    private javax.swing.JPanel PanelUser;
    private javax.swing.JPanel aboutuspan;
    private javax.swing.JLabel adminlb;
    private javax.swing.JTextField age;
    private javax.swing.JComboBox<String> citycombox;
    private javax.swing.JPanel concactuspan;
    private javax.swing.JTextField email;
    private javax.swing.JTextField first_name;
    private javax.swing.JLabel gender_L;
    private javax.swing.JComboBox gendercombobox;
    private javax.swing.JLabel info;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField last_name;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lbuser;
    private javax.swing.JLabel lbwelcome;
    private javax.swing.JLabel mail_L;
    private javax.swing.JLabel passlabel;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password_admin;
    private javax.swing.JPasswordField password_user;
    private javax.swing.JButton submitbutton;
    private javax.swing.JLabel txtExit;
    private javax.swing.JLabel userlb;
    private javax.swing.JButton userloginb;
    public static javax.swing.JTextField username;
    private javax.swing.JTextField username_admin;
    private javax.swing.JTextField username_user;
    private javax.swing.JPanel welcompanel;
    // End of variables declaration//GEN-END:variables
}
